from datenschutz import alternative_usernames, alt_usernames

mappinguntis = {
    ord(u"Ë"): u"E",
    ord(u"ë"): u"e",
    ord(u"Ï"): u"I",
    ord(u"ï"): u"i",
    ord(u"Ÿ"): u"Y",
    ord(u"ÿ"): u"y",
    ord(u"À"): u"A",
    ord(u"Á"): u"A",
    ord(u"Â"): u"A",
    ord(u"Ã"): u"A",
    ord(u"Å"): u"A",
    ord(u"Æ"): u"Ae",
    ord(u"Ç"): u"C",
    ord(u"Ì"): u"I",
    ord(u"Í"): u"I",
    ord(u"Î"): u"I",
    ord(u"Ð"): u"D",
    ord(u"Ñ"): u"N",
    ord(u"Ò"): u"O",
    ord(u"Ó"): u"O",
    ord(u"Õ"): u"O",
    ord(u"Ø"): u"Oe",
    ord(u"Œ"): u"Oe",
    ord(u"Ù"): u"U",
    ord(u"Ú"): u"U",
    ord(u"Û"): u"U",
    ord(u"Ý"): u"Y",
    ord(u"Þ"): u"Th",
    ord(u"à"): u"a",
    ord(u"á"): u"a",
    ord(u"â"): u"a",
    ord(u"ã"): u"a",
    ord(u"å"): u"a",
    ord(u"æ"): u"ae",
    ord(u"ç"): u"c",
    ord(u"ì"): u"i",
    ord(u"í"): u"i",
    ord(u"î"): u"i",
    ord(u"ð"): u"d",
    ord(u"ñ"): u"n",
    ord(u"ò"): u"o",
    ord(u"ó"): u"o",
    ord(u"õ"): u"o",
    ord(u"ø"): u"oe",
    ord(u"œ"): u"oe",
    ord(u"ù"): u"u",
    ord(u"ú"): u"u",
    ord(u"û"): u"u",
    ord(u"ý"): u"y",
    ord(u"þ"): u"Th",
    ord(u"Š"): u"S",
    ord(u"Ş"): u"S",
    ord(u"š"): u"s",
    ord(u"Č"): u"C",
    ord(u"ă"): u"a",
    ord(u"č"): u"c"
}

mappingusername = {
    ord(u"Ä"): u"Ae",
    ord(u"ä"): u"ae",
    ord(u"Ë"): u"E",
    ord(u"ë"): u"e",
    ord(u"Ï"): u"I",
    ord(u"ï"): u"i",
    ord(u"Ö"): u"Oe",
    ord(u"ö"): u"oe",
    ord(u"Ü"): u"Ue",
    ord(u"ü"): u"ue",
    ord(u"Ÿ"): u"Y",
    ord(u"ÿ"): u"y",
    ord(u"ß"): u"ss",
    ord(u"À"): u"A",
    ord(u"Á"): u"A",
    ord(u"Â"): u"A",
    ord(u"Ã"): u"A",
    ord(u"Å"): u"A",
    ord(u"Æ"): u"Ae",
    ord(u"Ç"): u"C",
    ord(u"È"): u"E",
    ord(u"É"): u"E",
    ord(u"Ê"): u"E",
    ord(u"Ì"): u"I",
    ord(u"Í"): u"I",
    ord(u"Î"): u"I",
    ord(u"Ð"): u"D",
    ord(u"Ñ"): u"N",
    ord(u"Ò"): u"O",
    ord(u"Ó"): u"O",
    ord(u"Ô"): u"O",
    ord(u"Õ"): u"O",
    ord(u"Ø"): u"Oe",
    ord(u"Œ"): u"Oe",
    ord(u"Ù"): u"U",
    ord(u"Ú"): u"U",
    ord(u"Û"): u"U",
    ord(u"Ý"): u"Y",
    ord(u"Þ"): u"Th",
    ord(u"à"): u"a",
    ord(u"á"): u"a",
    ord(u"â"): u"a",
    ord(u"ã"): u"a",
    ord(u"å"): u"a",
    ord(u"æ"): u"ae",
    ord(u"ç"): u"c",
    ord(u"è"): u"e",
    ord(u"é"): u"e",
    ord(u"ê"): u"e",
    ord(u"ì"): u"i",
    ord(u"í"): u"i",
    ord(u"î"): u"i",
    ord(u"ð"): u"d",
    ord(u"ñ"): u"n",
    ord(u"ò"): u"o",
    ord(u"ó"): u"o",
    ord(u"ô"): u"o",
    ord(u"õ"): u"o",
    ord(u"ø"): u"oe",
    ord(u"œ"): u"oe",
    ord(u"ù"): u"u",
    ord(u"ú"): u"u",
    ord(u"û"): u"u",
    ord(u"ý"): u"y",
    ord(u"þ"): u"Th",
    ord(u"Š"): u"S",
    ord(u"Ş"): u"S",
    ord(u"š"): u"s",
    ord(u"Č"): u"C",
    ord(u"ă"): u"a",
    ord(u"č"): u"c"
}

mappingklassen = {
    "05BS": "5b",
    "05AS": "5a",
    "05CS": "5c",
    "05DS": "5d",
    "05ES": "5e",
    "06AS": "6a",
    "06BS": "6b",
    "06CS": "6c",
    "06DS": "6d",
    "06ES": "6e",
    "07AS": "7a",
    "07BS": "7b",
    "07CS": "7c",
    "07DS": "7d",
    "07ES": "7e",
    "08AS": "8a",
    "08BS": "8b",
    "08CS": "8c",
    "08DS": "8d",
    "08ES": "8e",
    "09AS": "9a",
    "09BS": "9b",
    "09CS": "9c",
    "09DS": "9d",
    "09ES": "9e",
    "10AS": "10a",
    "10BS": "10b",
    "10CS": "10c",
    "10DS": "10d",
    "10ES": "10e",
    "EFS": "EF",
    "Q1S": "Q1",
    "Q2S": "Q2",
    "WKS": "WK",
    "TKS": "TK"
}

mappingSpaltentitelCSV = {
    0: "REALM",
    1: "AT_webuntisKurzname",
    2: "AT_webuntisUid",
    3: "US_lastName",
    4: "US_firstName",
    5: "webuntisKlasse",
    6: "US_email",
    7: "US_username",
    8: "AT_birthday",
    9: "AT_ncQuota",
    10: "CR_password",
    11: "AT_nc.memberOf",
    12: "AT_colloxUid",
    13: "AT_webuntisRole",
}

mappinggroups = {
    "Fach Biologie": "",
    "Fach Biologie - Lehrer": "FS-Bio",
    "Fach Bio: Mensch u. Umwelt": "",
    "Fach Bio: Mensch u. Umwelt - Lehrer": "",
    "Fach Chemie": "",
    "Fach Chemie - Lehrer": "FS-Ch",
    "Fach Deutsch": "",
    "Fach Deutsch - Lehrer": "FS-D",
    "Fach Englisch": "",
    "Fach Englisch - Lehrer": "FS-E",
    "Fach Englisch, Beginn in Jahrgangsklasse 5": "",
    "Fach Englisch, Beginn in Jahrgangsklasse 5 - Lehrer": "",
    "Fach Erdkunde": "",
    "Fach Erdkunde - Lehrer": "FS-Ek",
    "Fach Erdkunde ABI-Bac": "",
    "Fach Erdkunde ABI-Bac - Lehrer": "FS-Abi-Bac",
    "Fach evangelische Religionslehre": "",
    "Fach evangelische Religionslehre - Lehrer": "FS-eR",
    "Fach Französisch": "",
    "Fach Französisch - Lehrer": "FS-F",
    "Fach Französisch, Beginn in Jahrgangsstufe 5": "",
    "Fach Französisch, Beginn in Jahrgangsstufe 5 - Lehrer": "",
    "Fach Französisch, Beginn in Jahrgangsstufe 6": "",
    "Fach Französisch, Beginn in Jahrgangsstufe 6 - Lehrer": "",
    "Fach Französisch, Beginn in Jahrgangsklasse 7": "",
    "Fach Französisch, Beginn in Jahrgangsklasse 7 - Lehrer": "",
    "Fach Französisch, Beginn in Jahrgangsklasse 9": "",
    "Fach Französisch, Beginn in Jahrgangsklasse 9 - Lehrer": "",
    "Fach Französisch AbiBac": "",
    "Fach Französisch AbiBac - Lehrer": "",
    "Fach Geschichte": "",
    "Fach Geschichte - Lehrer": "FS-G",
    "Fach Geschichte ABI-Bac": "",
    "Fach Geschichte ABI-Bac - Lehrer": "",
    "Fach Muttersprache anstelle einer Pflichtfremdsprache - Griechisch": "",
    "Fach Muttersprache anstelle einer Pflichtfremdsprache - Griechisch - Lehrer": "",
    "Fach Jüdische Religionslehre": "",
    "Fach Jüdische Religionslehre - Lehrer": "",
    "Fach Italienisch": "",
    "Fach Italienisch - Lehrer": "FS-I",
    "Fach Informatik": "",
    "Fach Informatik - Lehrer": "FS-Inf",
    "Fach Japanisch, Beginn in Jahrgangsklasse 10": "",
    "Fach Japanisch, Beginn in Jahrgangsklasse 10 - Lehrer": "",
    "Fach katholische Religionslehre": "",
    "Fach katholische Religionslehre - Lehrer": "FS-kR",
    "Fach Kunsterziehung": "",
    "Fach Kunsterziehung - Lehrer": "FS-Ku",
    "Fach Latein": "",
    "Fach Latein - Lehrer": "FS-L",
    "Fach Lateinisch, Beginn in Jahrgangsklasse 6": "",
    "Fach Lateinisch, Beginn in Jahrgangsklasse 6 - Lehrer": "",
    "Fach Lateinisch, Beginn in Jahrgangsklasse 7": "",
    "Fach Lateinisch, Beginn in Jahrgangsklasse 7 - Lehrer": "",
    "Fach Mathematik": "",
    "Fach Mathematik - Lehrer": "FS-M",
    "Fach Musik": "",
    "Fach Musik - Lehrer": "FS-Mu",
    "Fach Naturwissenschaften": "",
    "Fach Naturwissenschaften - Lehrer": "FS-NW",
    "Fach Physik": "",
    "Fach Physik - Lehrer": "FS-Ph",
    "Fach Politik": "",
    "Fach Politik - Lehrer": "FS-SW",
    "Fach Projektkurs Wirtschaftsenglisch": "",
    "Fach Projektkurs Wirtschaftsenglisch - Lehrer": "",
    "Fach Philosophie": "",
    "Fach Philosophie - Lehrer": "FS-Pl",
    "Fach Praktische Philosophie": "",
    "Fach Praktische Philosophie - Lehrer": "FS-Pl",
    "Fach Russisch, Beginn in Jg. 10": "",
    "Fach Russisch, Beginn in Jg. 10 - Lehrer": "",
    "Fach Spanisch, Beginn in Jahrgangsklasse 8": "",
    "Fach Spanisch, Beginn in Jahrgangsklasse 8 - Lehrer": "",
    "Fach Schwimmen": "",
    "Fach Schwimmen - Lehrer": "",
    "Fach Sport": "",
    "Fach Sport - Lehrer": "FS-Sp",
    "Fach Sozialwissenschaften": "",
    "Fach Sozialwissenschaften - Lehrer": "FS-SW",
    "Fach Türkisch, Beginn in Jahrgangsklasse 8": "",
    "Fach Türkisch, Beginn in Jahrgangsklasse 8 - Lehrer": "",
    "Fach Unesco": "",
    "Fach Unesco - Lehrer": "FS-UN",
    "Fach VT Deutsch": "",
    "Fach VT Deutsch - Lehrer": "",
    "Fach VT Englisch": "",
    "Fach VT Englisch - Lehrer": "",
    "Fach MINT": "MINT",
    "Fach MINT - Lehrer": "FS-MINT",
    "Fach MINT - Schueler": "",
    "Fach VT Mathematik": "",
    "Fach VT Mathematik - Lehrer": "",
    "Gruppe Zustimmung-Presse-und-TV": "",
    "Gruppe Zustimmung-Presse-und-TV - Mitglieder": "",
    "Fach Foto AG": "",
    "Fach Foto AG - Lehrer": "",
    "Fach Theater AG": "",
    "Fach VT Französisch": "",
    "Fach VT Französisch - Lehrer": "",
    "Fach Theater AG - Lehrer": "",
    "Bereich Oberstufe - Lehrer": "Sek2-L",
    "Bereich Oberstufe": "",
    "Bereich Oberstufe - Bereichsleiter": "",
    "Fach Projektkurs Jugend forscht": "",
    "Fach Projektkurs Jugend forscht - Lehrer": "",
    "Fach Russisch, Beginn in Jahrgangsklasse 8": "",
    "Fach Russisch, Beginn in Jahrgangsklasse 8 - Lehrer": "",
    "Fach VT Mathe Ergänzung": "M-VT-S",
    "Fach VT Mathe Ergänzung - Lehrer": "M-VT-L",
    "Bereich Oberstufe - Schueler": "Sek2-S",
    "Fach Deutsch als Zielsprache": "DaZS",
    "Fach Deutsch als Zielsprache - Lehrer": "DaZS-L"
}

klassenliste = [
    "05AS23",
    "05BS23",
    "05CS23",
    "05DS23",
    "05ES23",
    "06AS23",
    "06BS23",
    "06CS23",
    "06DS23",
    "06ES23",
    "07AS23",
    "07BS23",
    "07CS23",
    "07DS23",
    "07ES23",
    "08AS23",
    "08BS23",
    "08CS23",
    "08DS23",
    "08ES23",
    "09AS23",
    "09BS23",
    "09CS23",
    "09DS23",
    "09ES23",
    "10AS23",
    "10BS23",
    "10CS23",
    "10DS23",
    "10ES23",
    "EFS23",
    "Q1S23",
    "Q2S23",
    "WKS23",
    "TKS23"
]